Numpy



In [2]:
import numpy as np
## create a array using numpy
## create a 1D array
arr1=np.array([1,2,3,4,56,54])
print(arr1)
print(type(arr1))
print(arr1.shape)  ## it is one dimesional array

[ 1  2  3  4 56 54]
<class 'numpy.ndarray'>
(6,)


In [4]:
arr2=np.array([12,3,4,2,4,5])
arr2.reshape(6,1) ## converted into 2 dimensional array

array([[12],
       [ 3],
       [ 4],
       [ 2],
       [ 4],
       [ 5]])

In [6]:
arr3=np.array([[23534,325,325,324],[34,23432,5425,235]])
print(type(arr3))
arr3.shape

<class 'numpy.ndarray'>


(2, 4)

In [7]:
print(np.arange(0,10,2))
print(np.arange(0,10,2).reshape(1,5))

[0 2 4 6 8]
[[0 2 4 6 8]]


In [9]:
print(np.ones((3,6)))

[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]


In [10]:
## identity matrix
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [11]:
## Attributes of Numpy Array
arr = np.array([[1, 2, 3], [4, 5, 6]])

print("Array:\n", arr)
print("Shape:", arr.shape)  # Output: (2, 3)
print("Number of dimensions:", arr.ndim)  # Output: 2
print("Size (number of elements):", arr.size)  # Output: 6
print("Data type:", arr.dtype)  # Output: int32 (may vary based on platform)
print("Item size (in bytes):", arr.itemsize)  # Output: 8 (may vary based on platform)

Array:
 [[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Number of dimensions: 2
Size (number of elements): 6
Data type: int64
Item size (in bytes): 8


In [12]:
## Numpy Vecotorized Operation
arr1=np.array([1,3,4,6,7])
arr2=np.array([2,4,57,3,53])

## element wise additon
print("addition",arr1+arr2)

## substration
print(arr1-arr2)

## multiply
print(arr1*arr2)

## division

print(arr1/arr2)

addition [ 3  7 61  9 60]
[ -1  -1 -53   3 -46]
[  2  12 228  18 371]
[0.5        0.75       0.07017544 2.         0.13207547]


In [14]:
## universion function
arr=np.array([2,2,3,5,3,54,3,5])

## sqaure root
print(np.sqrt(arr))

## exponential
print(np.exp(arr))

## sine
print(np.sin(arr))

## natural log
print(np.log(arr))

[1.41421356 1.41421356 1.73205081 2.23606798 1.73205081 7.34846923
 1.73205081 2.23606798]
[7.38905610e+00 7.38905610e+00 2.00855369e+01 1.48413159e+02
 2.00855369e+01 2.83075330e+23 2.00855369e+01 1.48413159e+02]
[ 0.90929743  0.90929743  0.14112001 -0.95892427  0.14112001 -0.55878905
  0.14112001 -0.95892427]
[0.69314718 0.69314718 1.09861229 1.60943791 1.09861229 3.98898405
 1.09861229 1.60943791]


In [15]:
arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print("Array : \n", arr)

Array : 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [16]:
print(arr[1:,1:3])

[[ 6  7]
 [10 11]]


In [18]:
print(arr[0][0])
print(arr[0:2,2:])

1
[[3 4]
 [7 8]]


In [19]:
arr[1:,2:]

array([[ 7,  8],
       [11, 12]])

In [20]:
## Modify array elements
arr[0,0]=100
print(arr)

[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [21]:
arr[1:]=100
print(arr)

[[100   2   3   4]
 [100 100 100 100]
 [100 100 100 100]]


In [23]:
## statistical concepts-- Normalization
## to have a mean of 0 and standard deviation of 1
data=np.array([2,3,5,3,5,35,3])

## calculate the mean and standard deviation
mean=np.mean(data)
print(mean)
std_dev=np.std(data)
print(data)

## Normalize the data

normalized_data=(data-mean)/std_dev
print("NOrmalised data: ",normalized_data)

8.0
[ 2  3  5  3  5 35  3]
NOrmalised data:  [-0.54194676 -0.4516223  -0.27097338 -0.4516223  -0.27097338  2.43876043
 -0.4516223 ]


In [24]:
data = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Mean
mean = np.mean(data)
print("Mean:", mean)

# Median
median = np.median(data)
print("Median:", median)

# Standard deviation
std_dev = np.std(data)
print("Standard Deviation:", std_dev)

# Variance
variance = np.var(data)
print("Variance:", variance)



Mean: 5.5
Median: 5.5
Standard Deviation: 2.8722813232690143
Variance: 8.25


In [25]:
## Logical operation
data=np.array([1,2,3,4,5,6,7,8,9,10])

data[(data>=5) & (data<=8)]

array([5, 6, 7, 8])